{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api_name",
    "query": {
     "query": "label_values(custom_api_response_time_seconds,$api_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Влажность ИЛИ температура когда видимость НИЗКАЯ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_visibility_km{city=\"Astana\"} > 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "МАКСИМАЛЬНАЯ скорость ветра по странаь",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (country) (weather_windspeed_kmh)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "СКОРОСТЬ ИЗМЕНЕНИЯ цены Bitcoin ($ в минуту)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(crypto_bitcoin_price_usd[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Изменение цены Bitcoin за последний час",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "crypto_bitcoin_price_usd - crypto_bitcoin_price_usd offset 1h",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Аптайм экспортера в часах",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exporter_uptime_seconds / 3600\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Топ-1 самая высокая цена криптовалюты",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, crypto_bitcoin_price_usd)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Предсказание температуры (линейная регрессия)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "predict_linear(weather_temperature_celsius{city=\"Astana\"}[30m], 300)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Волатильность цены Bitcoin (стандартное отклонение)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "stddev_over_time(crypto_bitcoin_price_usd[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Время ответа API (95-й перцентиль)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_response_time_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Скорость изменения температуры (°C в минуту)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(weather_temperature_celsius{city=\"Astana\"}[5m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя температура за последние 10 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "avg_over_time(weather_temperature_celsius{city=\"Astana\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}