{
 "title": "Database Exporter ",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "database" },
   {
    "name": "query0",
    "query": {
     "query": "label_values(pg_database_size_bytes,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "distribution of connections by status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum load over the last hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(rate(pg_stat_database_xact_commit[5m])[5m])[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of tables and rows",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_stat_user_tables_n_live_tup{datname=\"$query0\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pg_stat_user_tables_n_live_tup)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users with privileges",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_roles_connection_limit == -1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "active users",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(usename) (pg_stat_activity_count{datname=\"$query0\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Все транзакции и запросы (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(rate(pg_stat_database_xact_commit{datname=\"postgres\"}[5m]) + \r\n rate(pg_stat_database_xact_rollback{datname=\"postgres\"}[5m]) +\r\n rate(pg_stat_database_tup_returned{datname=\"postgres\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "reading inventensy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_user_tables_seq_scan{datname=\"$query0\"}[5m])) + (sum(rate(pg_stat_user_tables_idx_scan[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "exporter process start time(Uptime)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"postgresql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database size GB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"$query0\"} / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"$query0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}