{
 "title": "Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CPUcore",
    "query": {
     "query": "label_values(node_cpu_seconds_total,cpu)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Context switches в секунду",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество открытых файловых дескрипторов",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=\"node_exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сетевой трафик - исходящий (Mbit/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m]) * 8 / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime в секундах",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O — чтение и запись (байт/сек)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m]) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Сетевой трафик - входящий (Mbit/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m]) * 8 / 1000 / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Свободное место на диске (в GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load average (1, 5, 15 минут)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage (по ядрам)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_seconds_total - (rate(node_cpu_seconds_total{mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}